#include "image_data.h"
#include "display.h"

const uint16_t test_image[TEST_IMAGE_WIDTH * TEST_IMAGE_HEIGHT] =
    {
        TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_BLUE, TFT_BLUE, TFT_BLUE, TFT_BLUE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_BLUE, TFT_GREEN, TFT_GREEN, TFT_BLUE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_BLUE, TFT_GREEN, TFT_GREEN, TFT_BLUE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_BLUE, TFT_BLUE, TFT_BLUE, TFT_BLUE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_WHITE, TFT_RED,
        TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED, TFT_RED};
